name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: deploy on digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.PASSPHRASE }}

          script: |
            
            git clone https://github.com/auxibee/chimoney.git
            cd chimoney
            npm run setup:all
          
